### ISSUE TITLE
Módulo VIP corrompido 

### ISSUE THREAD

**Issue by solundev** [RootGC/JethJS#79]
_Devido a implementação da versão v13 da livraria Discord.JS muitas funções se tornaram **deprecated** ou seja, fizeram com que o módulo todo de VIP parasse de funcionar de forma completa e permanente, correções foram tentadas e mesmo assim o problema persiste, necessário reescrever o código por completo e remodular para algo melhor._

### 🚩 Erro ao criar cargo VIP:

```
2022-04-14T02:20:09.802222+00:00 app[worker.1]: /app/node_modules/discord.js/src/util/Util.js:476
2022-04-14T02:20:09.802235+00:00 app[worker.1]:     else if (Number.isNaN(color)) throw new TypeError('COLOR_CONVERT');
2022-04-14T02:20:09.802235+00:00 app[worker.1]:                                         ^
2022-04-14T02:20:09.802236+00:00 app[worker.1]: 
2022-04-14T02:20:09.802237+00:00 app[worker.1]: TypeError [COLOR_CONVERT]: Unable to convert color to a number.
2022-04-14T02:20:09.802237+00:00 app[worker.1]:     at resolveColor (/app/node_modules/discord.js/src/util/Util.js:476:41)
2022-04-14T02:20:09.802238+00:00 app[worker.1]:     at RoleManager.create (/app/node_modules/discord.js/src/managers/RoleManager.js:138:15)
2022-04-14T02:20:09.802238+00:00 app[worker.1]:     at vip.run (/app/src/commands/VIP/VIPCommand.js:183:31)
2022-04-14T02:20:09.802238+00:00 app[worker.1]:     at runMicrotasks (<anonymous>)
2022-04-14T02:20:09.802239+00:00 app[worker.1]:     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
2022-04-14T02:20:09.802239+00:00 app[worker.1]:   [Symbol(code)]: 'COLOR_CONVERT'
2022-04-14T02:20:09.802240+00:00 app[worker.1]: }
```

### 🚩 Erro ao tentar adicionar seu cargo VIP no usuário:

![image](https://user-images.githubusercontent.com/82925878/163301838-2832257d-c2c6-4f58-9a60-657e48acc212.png)

### 🙏 O QUE FAZER?

**O sistema deverá ser reescrito de forma que o usuário cadastrado como VIP dentro da database possa:**

- Criar seu cargo VIP
- Definir a cor de seu cargo VIP
- Personalizar seu cargo a qualquer momento
- Criar um canal VIP
- Personalizar este canal VIP a qualquer momento.

**EXTRAS IMPORTANTES:**

*Para segurança dos usuários e servidor, antes do cargo e canal VIP serem aprovados eles devem passar por uma verificação manual de nomes pelos staffers da Jeth em uma sala separada, que será criada como um ticket, e somente os staffers e o usuário terão acesso de ver/interagir. Aceitar ou recusar a criação do cargo e ou canal deve ser feito por um sistema de buttons onde somente um dos staffers da Jeth poderão realizar esta ação!*

**Comment by solundev** [comment]
**Atualização de erro:**

  _Ao utilizar comando `-vip cargo teste ` o cargo teste é criado porém a cor que deveria ser definida dentro da database não está sendo salvo, e o cargo está podendo ser criado múltiplas infinitas vezes._
  
- [x] TypeError [COLOR_CONVERT]: Unable to convert color to a number. **FIXED**

 _Outros erros anteriores se mantém._
 
 ![err](https://cdn.technologyreview.jp/wp-content/uploads/sites/2/2018/03/06010604/webp.net-gifmaker-2.gif)

**Comment by solundev** [comment]
**_Sistema refeito, aguardando correções extras de bugs!_**
