### ISSUE TITLE
MongoDB Error

### ISSUE THREAD

**Issue by solundev** [RootGC/JethJS#83]
**Um bug que necessita de uma alternativa dentro do código para ser resolvido.**

```Js
2022-05-02T05:02:27.684862+00:00 app[worker.1]: /app/node_modules/mongoose/lib/model.js:492
2022-05-02T05:02:27.684869+00:00 app[worker.1]:     parallelSave = new ParallelSaveError(this);
2022-05-02T05:02:27.684869+00:00 app[worker.1]:                    ^
2022-05-02T05:02:27.684870+00:00 app[worker.1]: 
2022-05-02T05:02:27.684871+00:00 app[worker.1]: ParallelSaveError: Can't save() the same doc multiple times in parallel. Document: 442774319819522059
2022-05-02T05:02:27.684872+00:00 app[worker.1]:     at Model.save (/app/node_modules/mongoose/lib/model.js:492:20)
2022-05-02T05:02:27.684872+00:00 app[worker.1]:     at Rep.run (/app/src/commands/Social/RepCommand.js:55:14)
2022-05-02T05:02:27.684873+00:00 app[worker.1]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)```

O erro é simples como já foi dito, procuro uma alternativa para o código solucionando este probleminha.

**Comment by solundev** [comment]
Solved
